from envparse import env

env.read_envfile('config.env')

BOT_API_TOKEN = env.str('BOT_API_TOKEN')

FIREBASE_CREDENTIALS_FILE = env.str('FIREBASE_CREDENTIALS_FILE')

STATISTICS_SERVICE_BASE_URL = env.str('STATISTICS_SERVICE_BASE_URL')

BILL_DATABASE_URL = env.str('BILL_DATABASE_URL')
BILL_DATABASE_PASSWORD = env.str('BILL_DATABASE_PASSWORD')
